### ISSUE TITLE
Abstract classes?

### ISSUE THREAD

**Issue by tylercollier** [lapistano/proxy-object#12]
How can I test an abstract class? I was hoping it would just work using this.

```
$myObj = new \lapistano\ProxyObject\ProxyBuilder('MyAbstractClass');
$result = $myObj->myProtectedMethodUnderTest();
```

but I get an error like this:

> PHP Fatal error:  Class Proxy_MyAbstractClass_f6efbaef contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods

Is this something this library can be used for?

**Comment by lapistano** [comment]
hi tyler, 
sorry for may late answer - I was in Iceland on vacation were I did not get any reception.

To your question:
you are doing it wring, sorry.

``` php
$myObj = new \lapistano\ProxyObject\ProxyBuilder('MyAbstractClass')
  ->setMethods(array(<YOUR_ABSTRACT_METHOS_HERE>))
  ->getProxy();
$result = $myObj->myProtectedMethodUnderTest();
```

**Comment by tylercollier** [comment]
Thanks for clarifying. I have no idea how I missed that, as I was using it successfully elsewhere for non abstract classes.
